### ISSUE TITLE
'Add custom dynamic entity data source' example under Layers not working for WPF application

### ISSUE THREAD

**Issue by tejabalu** [Esri/arcgis-maps-sdk-dotnet-samples#1297] opened 2023-09-22 03:40 UTC
This is the view that we're supposed to see: 
<img width="450" alt="image" src="https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/83402878/463ab2dd-489f-4d53-a29c-fec0c5040d0b">

But running the application, the view we see is this: 
<img width="1171" alt="image" src="https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/assets/83402878/b9c0e135-c28e-4008-8ca7-9f3ead59a54e">

We don't see the data being loaded in the map interface. I've also made sure to check that all the required offline files were downloaded with no luck.

Thanks!

**Comment by williambohrmann3** [comment] 2023-09-25 16:52
Hey @tejabalu thanks for checking offline files were downloaded. I'm unable to reproduce this on my Windows 10 PC when testing WPF .NET 6 and .NET Framework solutions. Note that there is limited data with the simulated data source - the data will only display for only a few minutes since we don't loop the data again. But it sounds like no data at all is displaying for you. Would you kindly answer the following?

1. Are you seeing this behavior in both WPF projects? 
2. Did you deploy the sample viewer app from the Microsoft Store or did you clone the repo?
3. If cloned, what configuration? e.g., Debug | x64
4. What version of Windows are you on?

**Comment by tejabalu** [comment] 2023-10-09 05:20
Hi! 

Thanks for your response! I've found a fix for this and raised a PR [here](https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/pull/1300)! 

1. Yes. I'm also seeing the same behavior in the WinUI project. The same sample does not exist for other frameworks like Maui. 
2. I'm seeing the same behavior in the app downloaded from the Microsoft Store and in the cloned repository. 
3. Debug | Any CPU
4. I've actually tested this on 2 machines with the same behavior. The machines have Windows 11 and Windows 11 Arm respectively. 

The issue was that the offline file name in the code did not match the actual file name being downloaded from the resource in the [link](https://www.arcgis.com/home/item.html?id=a8a942c228af4fac96baa78ad60f511f). The name of the file in the resource link is `AIS_MarineCadastre_SelectedVessels_CustomDataSource.jsonl`, whereas the code has the file name as `AIS_MarineCadastre_SelectedVessels_CustomDataSource.json`, with the wrong file extension. 

It's interesting that you are not seeing this behavior on your machine. My hypothesis would be that the link initially hosted the file name with the `json` extension, which was later changed to the `jsonl`. You might have had the file downloaded before this change was made, and the app was not redownloading the file. Could you please check what file you currently have in your PC, and if deleting it and prompting the app to redownload the file reproduces this behavior?

P.S.: Sorry about my delayed response, I had limited access to my machine.

**Comment by williambohrmann3** [comment] 2023-10-10 00:12
@tejabalu thank you for the detailed response and triage! I am now able to reproduce on all platforms. Just so you know, we do offer this [sample](https://github.com/Esri/arcgis-maps-sdk-dotnet-samples/tree/main/src/MAUI/Maui.Samples/Samples/Layers/AddCustomDynamicEntityDataSource) in .NET MAUI. Looking at the PR now.

**Comment by tejabalu** [comment] 2023-10-10 01:29
Nice, I updated the PR with the change for Maui too!

**Comment by williambohrmann3** [comment] 2023-10-10 18:25
Fixed by @tejabalu

**Closed by williambohrmann3** 2023-10-10 18:25 UTC
